[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['npm install --production']

[phases.build]
cmds = ['echo "No build step needed for backend"']

[start]
cmd = 'node server/index.js'

[variables]
PORT = '8080'